/*  -----------EQUIPO AGP------------
    INTEGRANTES:
    JOSÉ GIOVANNI CARRILLO RUBIO
    OCHOA MEZA PAÚL ALEJANDRO
    MEDINA SOTO CARLOS ALAN
*/
import javax.swing.JOptionPane;
public class Ventana extends javax.swing.JFrame {
    METODOS obj = new METODOS();
    int arreglo[];
    int save[]; 

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        int tam = Integer.parseInt(JOptionPane.showInputDialog(null,"Tamaño del vector:"));
        arreglo = new int[tam];
        String cad="";
        for(int i =0; i<arreglo.length; i++){
            arreglo[i] = (int)(Math.random()*1000);
            cad+= "["+arreglo[i]+"] ";
        }
        initComponents();
        txtVector.setText(cad);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        btnRadix = new javax.swing.JButton();
        btnShell = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnQuick = new javax.swing.JButton();
        btnMezclaNat = new javax.swing.JButton();
        btnInter = new javax.swing.JButton();
        btnMezclaDirecta = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtVector = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblResp = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setText("BURBUJA");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnRadix.setText("RADIX");
        btnRadix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRadixActionPerformed(evt);
            }
        });

        btnShell.setText("SHELLSORT");
        btnShell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShellActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Vector");

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Métodos de Ordenamiento");

        btnQuick.setText("QUICKSORT");
        btnQuick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuickActionPerformed(evt);
            }
        });

        btnMezclaNat.setText("MEZCLA NATURAL");
        btnMezclaNat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMezclaNatActionPerformed(evt);
            }
        });

        btnInter.setText("INTERCALACIÓN");
        btnInter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInterActionPerformed(evt);
            }
        });

        btnMezclaDirecta.setText("MEZCLA DIRECTA");
        btnMezclaDirecta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMezclaDirectaActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(txtVector);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(btnInter))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(btnRadix, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                                .addComponent(btnQuick)
                                .addGap(33, 33, 33)
                                .addComponent(btnShell))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnMezclaDirecta)
                                .addGap(39, 39, 39)
                                .addComponent(btnMezclaNat)
                                .addGap(10, 10, 10))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(btnRadix)
                    .addComponent(btnQuick)
                    .addComponent(btnShell))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMezclaNat)
                    .addComponent(btnInter)
                    .addComponent(btnMezclaDirecta))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(49, 49, 49)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(123, Short.MAX_VALUE)))
        );

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));

        jScrollPane1.setViewportView(lblResp);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        salvar();
        String respuesta = obj.Bubble(arreglo);
        lblResp.setText("Burbuja: "+respuesta);
        for(int i=0; i<arreglo.length; i++){
            arreglo[i] = save[i];
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnRadixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRadixActionPerformed
        salvar();
        String respuesta = obj.Radix(arreglo);
        lblResp.setText("Radix: "+respuesta);
        for(int i=0; i<arreglo.length; i++){
            arreglo[i] = save[i];
        }
    }//GEN-LAST:event_btnRadixActionPerformed

    private void btnShellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShellActionPerformed
        salvar();
        String respuesta = obj.Shellsort(arreglo);
        lblResp.setText("Shellsort: "+respuesta);
        for(int i=0; i<arreglo.length; i++){
            arreglo[i] = save[i];
        }
    }//GEN-LAST:event_btnShellActionPerformed

    private void btnQuickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuickActionPerformed
        salvar();
        String respuesta = obj.Quicksort(arreglo, 0, arreglo.length-1);
        lblResp.setText("Quicksort: "+respuesta);
        for(int i=0; i<arreglo.length; i++){
            arreglo[i] = save[i];
        }
    }//GEN-LAST:event_btnQuickActionPerformed

    private void btnMezclaNatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMezclaNatActionPerformed
        salvar();
        obj.mezclaNatural(arreglo);
        String resp = obj.imprimir(arreglo);
        lblResp.setText("Mezcla natural: "+resp);
        for(int i=0; i<arreglo.length; i++){
            arreglo[i] = save[i];
        }
    }//GEN-LAST:event_btnMezclaNatActionPerformed

    private void btnInterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInterActionPerformed
        salvar();
        int tamano = Integer.parseInt(JOptionPane.showInputDialog(null,"Tamaño del segundo vector:"));
        int [] arreglo2 = new int[tamano];
        llenarVector(arreglo2);
        obj.Burbuja(arreglo);
        obj.Burbuja(arreglo2);
        String respuesta = obj.intercalacion(arreglo, arreglo2);
        String v1 = obj.imprimir(arreglo2);
        lblResp.setText("Vector 2: "+v1+"\nIntercalación:"+respuesta);
        for(int i=0; i<arreglo.length; i++){
            arreglo[i] = save[i];
        }
    }//GEN-LAST:event_btnInterActionPerformed

    private void btnMezclaDirectaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMezclaDirectaActionPerformed
        salvar();
        String resp = obj.imprimir(obj.mezclaDirecta(arreglo));
        lblResp.setText("Mezcla directa: "+resp);
        for(int i=0; i<arreglo.length; i++){
            arreglo[i] = save[i];
        }
    }//GEN-LAST:event_btnMezclaDirectaActionPerformed
    private void salvar(){
        /*Con esta función salvamos o guardamos los valores de el vector original
        Con el fin de evitar que se altere cuando se ordena a través de los botones para
        aplicar los ordenamientos*/
        save = new int[arreglo.length];
        for(int i=0; i<arreglo.length; i++){
            save[i] = arreglo[i];
        }
    }
    
    private void llenarVector(int[] vector){
        for(int i=0; i<vector.length; i++){
            vector[i] = (int)(Math.random()*1000);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInter;
    private javax.swing.JButton btnMezclaDirecta;
    private javax.swing.JButton btnMezclaNat;
    private javax.swing.JButton btnQuick;
    private javax.swing.JButton btnRadix;
    private javax.swing.JButton btnShell;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane lblResp;
    private javax.swing.JTextPane txtVector;
    // End of variables declaration//GEN-END:variables
}
